# -*- coding: utf-8 -*-
"""
🤖 BOT KELAS AUTOMATION - TEMPLATE v3.0.0
Tinggal isi data.json, lalu jalankan!
"""
import json, pyperclip, time, os, platform
from datetime import datetime, timedelta
from config import ConfigManager
from logger import log_info, log_error, log_warning, log_event, log_debug
from validators import Validator
from whatsapp_handler import WhatsAppHandler

VERSION = "3.0.0-Template"
HARI_INDONESIA = ["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"]

# Warna terminal
CYAN = '\033[96m'
GREEN = '\033[92m'
YELLOW = '\033[93m'
RED = '\033[91m'
BOLD = '\033[1m'
RESET = '\033[0m'

# ---------- Utility Functions ----------
def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def print_header(title):
    print(f"{CYAN}{'='*55}{RESET}")
    print(f"{BOLD}{YELLOW}   {title.upper()}{RESET}")
    print(f"{CYAN}   v{VERSION}{RESET}")
    print(f"{CYAN}{'='*55}{RESET}")

def print_separator():
    print(f"{CYAN}{'-'*55}{RESET}")

def print_success(msg): print(f"{GREEN}✅ {msg}{RESET}")
def print_error(msg):   print(f"{RED}❌ {msg}{RESET}")
def print_warning(msg): print(f"{YELLOW}⚠️  {msg}{RESET}")
def print_info(msg):    print(f"{CYAN}ℹ️  {msg}{RESET}")

def safe_input(prompt, allow_cancel=False):
    try:
        result = input(f"{YELLOW}{prompt}{RESET}").strip()
        if allow_cancel and result.lower() == 'b':
            return None, True
        return result, False
    except (KeyboardInterrupt, Exception) as e:
        log_error(f"Input error: {e}")
        return None, True

def wait_for_key(seconds=1.5):
    try: time.sleep(seconds)
    except KeyboardInterrupt: pass

# ---------- Task Management ----------
def cleanup_expired_tasks(data):
    tasks = data.get("tugas", [])
    today = datetime.now().date()
    valid_tasks = []
    removed = 0
    for t in tasks:
        try:
            d = datetime.strptime(t["deadline"], "%Y-%m-%d").date()
            if d >= today:
                valid_tasks.append(t)
            else:
                removed += 1
        except:
            valid_tasks.append(t)
    if removed:
        data['tugas'] = valid_tasks
        print_info(f"Auto-Cleanup: {removed} tugas expired dihapus")
    return data

def get_next_school_day(data):
    now = datetime.now()
    offset = 1 if now.hour >= 17 else 0
    for i in range(offset, 8):
        check = now + timedelta(days=i)
        day = HARI_INDONESIA[check.weekday()]
        if day in data.get("jadwal", {}):
            return day, check
    return None, None

def get_seragam(hari, tgl, data):
    aturan = data.get("seragam", {}).get(hari)
    if not aturan: return "Bebas"
    if isinstance(aturan, str): return aturan
    if isinstance(aturan, dict):
        try:
            week = tgl.isocalendar()[1]
            key = "minggu_seragam" if week % 2 == 0 else "minggu_bebas"
            return aturan.get(key, "Bebas")
        except: return "Bebas"
    return "Bebas"

def format_message(hari, tgl, data):
    try:
        jadwal = list(dict.fromkeys(data.get("jadwal", {}).get(hari, [])))
        piket = data.get("piket", {}).get(hari, ["-"])
        seragam = get_seragam(hari, tgl, data)
        teks  = f"*INFO KELAS - {hari.upper()}*\n"
        teks += f"📅 {tgl.strftime('%d/%m/%Y')}\n"
        teks += f"👕 Seragam: *{seragam}*\n\n"
        teks += "*📚 JADWAL:*\n"
        teks += "\n".join([f"• {m}" for m in jadwal]) if jadwal else "• Libur"
        teks += f"\n\n*🧹 PIKET:*\n• {', '.join(piket)}\n\n"
        teks += "*📝 TUGAS:*\n"
        tugas = []
        today = datetime.now().date()
        for t in sorted(data.get("tugas", []), key=lambda x: x.get("deadline", "9999-12-31")):
            try:
                d = datetime.strptime(t["deadline"], "%Y-%m-%d").date()
                sisa = (d - today).days
                if sisa < 0: continue
                status = "🔥 HARI INI" if sisa==0 else "⚠️ BESOK" if sisa==1 else f"⏳ {sisa} hari"
                tugas.append(f"• {t['mapel']}: {t['deskripsi']} ({status})")
            except: continue
        teks += "\n".join(tugas) if tugas else "• Tidak ada tugas"
        teks += f"\n\n_Generated by {data.get('config',{}).get('bot_name','Bot')}_"
        return teks
    except Exception as e:
        log_error(f"Format error: {e}")
        return "Gagal membuat pesan"

def preview_message(message, hari):
    clear_screen()
    print_header("Preview Pesan")
    print_separator()
    print(message)
    print_separator()
    print(f"\n{BOLD}Lanjutkan kirim?{RESET}")
    val, cancel = safe_input("(y/n): ", allow_cancel=True)
    return (not cancel and val and val.lower() == 'y')

# ---------- Menu ----------
def menu_task_management(config, mode):
    clear_screen()
    data = config.get_all()
    tasks = data.get("tugas", [])
    print_header(f"{mode.capitalize()} Tugas")
    if mode in ["edit","hapus"] and not tasks:
        print_error("Tidak ada tugas!")
        wait_for_key(1.5)
        return
    if mode in ["edit","hapus"]:
        for i, t in enumerate(tasks,1):
            print(f"{i}. [{t.get('deadline','?')}] {t.get('mapel','?')} - {t.get('deskripsi','?')}")
        inp, cancel = safe_input("Pilih nomor (b=batal): ", allow_cancel=True)
        if cancel or not inp: return
        is_val, idx = Validator.validate_index(inp, len(tasks))
        if not is_val:
            print_error(idx)
            wait_for_key(1)
            return
    if mode == "tambah":
        # Input mapel
        while True:
            m, cancel = safe_input("📖 Mapel: ", allow_cancel=True)
            if cancel: return
            ok, mapel = Validator.validate_string(m, "Mapel", min_length=2)
            if ok: break
            print_error(mapel)
        # Input deskripsi
        while True:
            d, cancel = safe_input("📝 Deskripsi: ", allow_cancel=True)
            if cancel: return
            ok, desk = Validator.validate_string(d, "Deskripsi", min_length=3)
            if ok: break
            print_error(desk)
        # Input deadline
        while True:
            dl, cancel = safe_input("📅 Deadline (YYYY-MM-DD): ", allow_cancel=True)
            if cancel: return
            ok, date = Validator.validate_date(dl)
            if ok:
                deadline = date.strftime("%Y-%m-%d")
                break
            print_error("Format salah, contoh: 2026-05-20")
        tasks.append({"mapel": mapel, "deskripsi": desk, "deadline": deadline})
        print_success("Tugas ditambahkan!")
        log_event("Tambah tugas", f"{mapel} - {deadline}")
    elif mode == "edit":
        task = tasks[idx]
        print(f"\nEdit: {task.get('mapel')}")
        new_mapel, _ = safe_input(f"Mapel [{task['mapel']}]: ")
        if new_mapel:
            ok, val = Validator.validate_string(new_mapel, "Mapel", min_length=2)
            if ok: task['mapel'] = val
        new_desc, _ = safe_input(f"Deskripsi [{task['deskripsi']}]: ")
        if new_desc:
            ok, val = Validator.validate_string(new_desc, "Deskripsi", min_length=3)
            if ok: task['deskripsi'] = val
        new_dl, _ = safe_input(f"Deadline [{task['deadline']}]: ")
        if new_dl:
            ok, val = Validator.validate_date(new_dl)
            if ok: task['deadline'] = val.strftime("%Y-%m-%d")
        print_success("Tugas diperbarui!")
        log_event("Edit tugas", task.get('mapel'))
    elif mode == "hapus":
        task = tasks[idx]
        conf, cancel = safe_input(f"Hapus '{task['mapel']}'? (y/n): ")
        if not cancel and conf and conf.lower() == 'y':
            removed = tasks.pop(idx)
            print_success("Tugas dihapus!")
            log_event("Hapus tugas", removed.get('mapel'))
        else:
            print_warning("Dibatalkan")
            wait_for_key(1)
            return
    config.set('tugas', tasks)
    config.save()
    wait_for_key(1)

def menu_view_tasks(config):
    clear_screen()
    print_header("Daftar Tugas")
    tasks = config.get_all().get("tugas", [])
    if not tasks:
        print_warning("Tidak ada tugas")
        wait_for_key(1.5)
        return
    today = datetime.now().date()
    for i, t in enumerate(sorted(tasks, key=lambda x: x.get("deadline","9999-12-31")), 1):
        try:
            d = datetime.strptime(t["deadline"], "%Y-%m-%d").date()
            sisa = (d - today).days
            color = RED if sisa<=0 else YELLOW if sisa==1 else GREEN
            status = "🔥 HARI INI" if sisa==0 else "⚠️ BESOK" if sisa==1 else f"⏳ {sisa} hari"
            print(f"{i}. {color}{t['mapel']}{RESET}")
            print(f"   {t['deskripsi']}")
            print(f"   Deadline: {t['deadline']} ({status})\n")
        except: print(f"{i}. Error menampilkan tugas")
    wait_for_key(2)

# ---------- Main ----------
def main():
    log_info("Bot template dimulai")
    config = ConfigManager()
    if config.get('app_settings.backup_on_startup', True):
        config.backup()
    if config.get('app_settings.auto_cleanup_expired_tasks', True):
        data = config.get_all()
        data = cleanup_expired_tasks(data)
        config.data = data
        config.save()
    ok, missing = config.validate_required_fields()
    if not ok:
        clear_screen()
        print_error("Data belum lengkap:")
        for f in missing: print(f"  - {f}")
        print_info("Isi data.json dulu ya!")
        wait_for_key(2)
        return
    while True:
        config.reload()
        data = config.get_all()
        clear_screen()
        print_header(data.get('config',{}).get('bot_name','Bot'))
        print(f"{BOLD}Menu:{RESET}\n")
        print("1. 📋 Copy Info")
        print("2. 🚀 Kirim Otomatis (WhatsApp)")
        print("3. 📖 Lihat Tugas")
        print("4. ➕ Tambah Tugas")
        print("5. ✏️  Edit Tugas")
        print("6. 🗑️  Hapus Tugas")
        print("7. ❌ Keluar")
        ch, cancel = safe_input("\nPilih: ", allow_cancel=True)
        if cancel or not ch: continue
        is_val, choice = Validator.validate_menu_choice(ch, 1, 7)
        if not is_val:
            print_error(choice)
            wait_for_key(1)
            continue
        if choice in ["1","2"]:
            hari, tgl = get_next_school_day(data)
            if not hari:
                print_error("Jadwal tidak ditemukan di data.json")
                wait_for_key(2)
                continue
            msg = format_message(hari, tgl, data)
            pyperclip.copy(msg)
            if choice == "1":
                clear_screen()
                print_header("Copy Mode")
                wh = WhatsAppHandler(config)
                print_info(f"Teks disalin! Paste: {wh.get_paste_key_display()}")
                print_separator()
                print(msg)
                print_separator()
                wait_for_key(2)
                log_event("Pesan disalin", hari)
            else:
                if not preview_message(msg, hari):
                    continue
                gid = config.get('config.group_id', '').strip()
                if not gid:
                    print_error("Group ID kosong! Isi di data.json")
                    wait_for_key(2)
                    continue
                ok, _ = Validator.validate_group_id(gid)
                if not ok:
                    print_error("Group ID tidak valid")
                    wait_for_key(2)
                    continue
                print("\n⏳ Mengirim...")
                wh = WhatsAppHandler(config)
                success, result = wh.send_automated(msg)
                if success:
                    print_success(result)
                    log_event("Kirim sukses", hari)
                else:
                    print_error(result)
                wait_for_key(2)
        elif choice == "3": menu_view_tasks(config)
        elif choice == "4": menu_task_management(config, "tambah")
        elif choice == "5": menu_task_management(config, "edit")
        elif choice == "6": menu_task_management(config, "hapus")
        elif choice == "7":
            clear_screen()
            print(f"{GREEN}Dadah! 👋{RESET}")
            log_event("Bot ditutup")
            break

if __name__ == "__main__":
    try: main()
    except KeyboardInterrupt:
        print(f"\n{YELLOW}Dihentikan.{RESET}")
    except Exception as e:
        print(f"{RED}Error: {e}{RESET}")
        log_error(f"Error: {e}")
